CXXFLAGS = -O0 -g -Wall -Wextra -std=c99
LFLAGS   = -fobjc-arc -framework Cocoa -framework OpenGL
TARGET   = main
SRC      = $(wildcard ./src/*.c)

$(TARGET): $(SRC) src/sokol.m
	$(CC) -o $(TARGET) $^ $(CXXFLAGS) $(LFLAGS)

clean:
	-$(RM) -rf $(TARGET).dSYM/ $(TARGET)
